[build]
  # Build command for React app
  command = "npm run build"
  
  # Publish directory
  publish = "dist"
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

# Disable secrets scanning for this project
[build.processing]
  skip_processing = false

# Secrets scanning configuration
[build.processing.secrets]
  enabled = false
  omit_paths = ["src/lib/firebase.ts", "dist/**"]
  omit_keys = ["VITE_FIREBASE_API_KEY", "VITE_FIREBASE_PROJECT_ID", "VITE_FIREBASE_APP_ID", "VITE_FIREBASE_AUTH_DOMAIN", "VITE_FIREBASE_MEASUREMENT_ID", "VITE_FIREBASE_MESSAGING_SENDER_ID", "VITE_FIREBASE_STORAGE_BUCKET"]

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
